name: main

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
        
env:
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_PROJECT_ID: 6207
  ALLURE_ENDPOINT: https://testing.allure.aws.qameta.in/

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

      - name: Build with Gradle
        run: |
          echo "hello world"
          export $(allurectl job-run env)
          printenv | grep ALLURE_
        
      - name: ALLURE_JOB_RUN_URL
        run: |
          export $(allurectl job-run env)
          export ALLURE_JOB_RUN_URL=$(allurectl job-run env | grep ALLURE_JOB_RUN_URL | cut -d "=" -f 2)
          echo "Report link: $ALLURE_JOB_RUN_URL | View Report"

